import { getSupabaseBrowserClient } from '../supabase/browser';
import type { ProjectBlockRow, ProjectRow } from '../../types/database';

type Media={url:string;width:number;height:number;alt:string;caption?:string};
type Block=ProjectBlockRow;
const types=[['intro','Section Title'],['text','Text'],['fullImage','Full Image'],['imageGrid','Two Column Images'],['gallery','Gallery'],['imageText','Image + Text'],['video','Video'],['spacer','Spacer']] as const;
const esc=(value:unknown)=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]!));
const lines=(value:unknown)=>Array.isArray(value)?value.join('\n'):String(value??'');
const field=(label:string,key:string,value:unknown,area=false)=>`<div class="admin-field"><label>${label}</label>${area?`<textarea data-field="${key}">${esc(lines(value))}</textarea>`:`<input data-field="${key}" value="${esc(value)}"/>`}</div>`;
const mediaFields=(media:Partial<Media>={},prefix='media')=>`<div class="admin-inline-image" data-media-group="${prefix}">${media.url?`<img class="admin-media-preview" src="${esc(media.url)}" alt=""/>`:''}${field('图片 URL',`${prefix}.url`,media.url)}${field('替代文字',`${prefix}.alt`,media.alt)}${field('说明',`${prefix}.caption`,media.caption)}<div class="admin-grid-2">${field('宽度',`${prefix}.width`,media.width)}${field('高度',`${prefix}.height`,media.height)}</div><div class="admin-upload"><input type="file" accept="image/*" data-block-upload="${prefix}"/><progress hidden></progress><button type="button" class="admin-secondary" data-clear-media="${prefix}">移除引用</button></div></div>`;
const defaults:Record<string,Record<string,unknown>>={
  intro:{label:'01 / Context',heading:'章节标题',description:['项目背景内容。']},text:{eyebrow:'',heading:'文字标题',body:['正文内容。'],alignment:'left'},
  fullImage:{image:{media:{url:'',width:1600,height:1000,alt:'作品图片'},fit:'contain'}},imageGrid:{columns:2,images:[]},gallery:{columns:3,images:[]},
  imageText:{imagePosition:'left',image:{media:{url:'',width:1200,height:900,alt:'作品图片'},fit:'contain'},eyebrow:'',heading:'图文标题',body:['图文说明。']},
  video:{title:'项目视频',source:{kind:'external',url:''},width:1920,height:1080,caption:''},spacer:{size:'medium'},
};

class AdminProjectEditor extends HTMLElement{
  client=getSupabaseBrowserClient(); projectId=this.dataset.projectId!; project?:ProjectRow; blocks:Block[]=[]; timer=0; cover:Media|null=null;
  form=this.querySelector<HTMLFormElement>('[data-project-form]')!; list=this.querySelector<HTMLElement>('[data-block-list]')!; state=this.querySelector<HTMLElement>('[data-save-state]')!;
  connectedCallback(){this.setup();void this.load();}
  setup(){
    this.querySelector('[data-save]')?.addEventListener('click',()=>void this.saveAll());
    this.form?.addEventListener('input',()=>this.queueSave());
    this.querySelector('[data-add-block]')?.replaceChildren(...types.map(([type,label])=>{const button=document.createElement('button');button.type='button';button.className='admin-secondary';button.textContent=`＋ ${label}`;button.addEventListener('click',()=>void this.add(type));return button;}));
    const upload=this.querySelector<HTMLInputElement>('[data-cover-upload]');upload?.addEventListener('change',()=>upload.files?.[0]&&void this.upload(upload.files[0],'cover'));
    this.querySelector('[data-remove-cover]')?.addEventListener('click',()=>{this.cover=null;this.showCover();this.queueSave();});
  }
  async load(){if(!this.client)return this.fail('Supabase 未配置。');const {data,error}=await this.client.from('projects').select('*, project_blocks(*)').eq('id',this.projectId).single();if(error||!data)return this.fail(error?.message??'项目不存在或已删除。');const record=data as ProjectRow & {project_blocks:ProjectBlockRow[]};const {project_blocks,...project}=record;this.project=project;this.blocks=[...project_blocks].sort((a,b)=>a.sort_order-b.sort_order);this.cover=project.cover_image as Media|null;this.fill();this.renderBlocks();this.querySelector<HTMLElement>('[data-editor]')!.hidden=false;}
  fail(message:string){const box=this.querySelector<HTMLElement>('[data-editor-error]')!;box.hidden=false;box.textContent=message;}
  fill(){if(!this.project)return;this.querySelector<HTMLElement>('[data-project-heading]')!.textContent=this.project.title;for(const [key,value] of Object.entries(this.project)){const input=this.form.elements.namedItem(key);if(input instanceof HTMLInputElement){if(input.type==='checkbox')input.checked=Boolean(value);else input.value=String(value??'');}else if(input instanceof HTMLTextAreaElement||input instanceof HTMLSelectElement)input.value=String(value??'');}this.cover=this.project.cover_image as Media|null;const alt=this.form.elements.namedItem('cover_alt') as HTMLInputElement;alt.value=this.cover?.alt??'';this.showCover();}
  showCover(){const img=this.querySelector<HTMLImageElement>('[data-cover-preview]')!;img.hidden=!this.cover?.url;if(this.cover?.url)img.src=this.cover.url;}
  queueSave(){this.state.textContent='有未保存修改';clearTimeout(this.timer);this.timer=window.setTimeout(()=>void this.saveAll(),800);}
  values(){const data=new FormData(this.form);const nullable=(name:string)=>String(data.get(name)??'').trim()||null;const slug=String(data.get('slug')??'').trim();return {title:String(data.get('title')),subtitle:nullable('subtitle'),slug,cover_image:this.cover?{...this.cover,alt:String(data.get('cover_alt')||this.cover.alt)}:null,category:String(data.get('category')),year:Number(data.get('year')),client:nullable('client'),role:nullable('role'),duration:nullable('duration'),summary:String(data.get('summary')),description:nullable('description'),featured:data.get('featured')==='on',status:String(data.get('status')) as 'draft'|'published',theme_background:nullable('theme_background')};}
  async saveAll(){if(!this.client||!this.project)return;clearTimeout(this.timer);if(!this.form.reportValidity())return;const value=this.values();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value.slug)){this.state.textContent='Slug 格式不正确';return;}this.state.textContent='保存中…';const {data:duplicate}=await this.client.from('projects').select('id').eq('slug',value.slug).neq('id',this.projectId).maybeSingle();if(duplicate){this.state.textContent='保存失败：Slug 已存在';return;}const {error}=await this.client.from('projects').update(value).eq('id',this.projectId);if(error){this.state.textContent=`保存失败：${error.message}`;return;}this.project={...this.project,...value,updated_at:new Date().toISOString()};this.querySelector<HTMLElement>('[data-project-heading]')!.textContent=value.title;this.state.textContent='已保存';}
  renderBlocks(){this.list.replaceChildren(...this.blocks.map((block,index)=>this.blockElement(block,index)));}
  blockElement(block:Block,index:number){const card=document.createElement('article');card.className='admin-block';card.draggable=true;card.dataset.id=block.id;const label=types.find(([type])=>type===block.type)?.[1]??block.type;card.innerHTML=`<header class="admin-block-head"><span class="admin-handle">⋮⋮</span><strong>${String(index+1).padStart(2,'0')} · ${esc(label)}</strong><div class="admin-block-toolbar"><button type="button" class="admin-icon-button" data-copy>复制</button><button type="button" class="admin-icon-button" data-delete>删除</button></div></header><div class="admin-block-body">${this.fields(block)}</div>`;
    card.addEventListener('input',()=>this.queueBlock(block,card));card.querySelector('[data-delete]')?.addEventListener('click',()=>void this.removeBlock(block));card.querySelector('[data-copy]')?.addEventListener('click',()=>void this.copy(block));
    card.querySelectorAll<HTMLInputElement>('[data-block-upload]').forEach(input=>input.addEventListener('change',()=>input.files?.[0]&&void this.upload(input.files[0],'block',card,input.dataset.blockUpload)));
    card.querySelector<HTMLButtonElement>('[data-add-image]')?.addEventListener('click',async()=>{const content=structuredClone(block.content as any);const limit=block.type==='imageGrid'?2:20;if((content.images?.length??0)>=limit){alert(block.type==='imageGrid'?'双图模块最多两张图片。':'单个 Gallery 最多 20 张图片。');return;}content.images??=[];content.images.push({media:{url:'',width:1600,height:1000,alt:'作品图片'},fit:'contain'});block.content=content;await this.client?.from('project_blocks').update({content}).eq('id',block.id);this.renderBlocks();});
    card.querySelector<HTMLInputElement>('[data-block-video]')?.addEventListener('change',event=>{const input=event.currentTarget as HTMLInputElement;if(input.files?.[0])void this.uploadVideo(input.files[0],block,card);});
    card.querySelectorAll<HTMLButtonElement>('[data-clear-media]').forEach(button=>button.addEventListener('click',()=>{const prefix=button.dataset.clearMedia!;card.querySelectorAll<HTMLInputElement>(`[data-field^="${prefix}."]`).forEach(input=>input.value='');button.closest('.admin-inline-image')?.querySelector('img')?.remove();this.queueBlock(block,card);}));
    card.addEventListener('dragstart',()=>card.classList.add('is-dragging'));card.addEventListener('dragend',()=>{card.classList.remove('is-dragging');void this.reorder();});card.addEventListener('dragover',event=>{event.preventDefault();const dragged=this.list.querySelector<HTMLElement>('.is-dragging');if(!dragged||dragged===card)return;const box=card.getBoundingClientRect();this.list.insertBefore(dragged,event.clientY<box.top+box.height/2?card:card.nextSibling);});return card;}
  fields(block:Block){const c=block.content as any;
    if(block.type==='intro')return field('Section label','label',c.label)+field('标题','heading',c.heading)+field('正文（每行一段）','description',c.description,true);
    if(block.type==='text')return field('Eyebrow','eyebrow',c.eyebrow)+field('标题','heading',c.heading)+field('正文（每行一段）','body',c.body,true)+`<div class="admin-field"><label>对齐</label><select data-field="alignment"><option value="left" ${c.alignment==='left'?'selected':''}>左</option><option value="center" ${c.alignment==='center'?'selected':''}>中</option><option value="right" ${c.alignment==='right'?'selected':''}>右</option></select></div>`;
    if(block.type==='fullImage')return mediaFields(c.image?.media,'image.media')+field('Caption','image.media.caption',c.image?.media?.caption)+`<div class="admin-field"><label>显示方式</label><select data-field="image.fit"><option value="contain">Contain</option><option value="cover" ${c.image?.fit==='cover'?'selected':''}>Cover</option></select></div>`;
    if(block.type==='imageGrid'||block.type==='gallery'){const images=(c.images??[]) as any[];return `<div class="admin-field"><label>列数</label><select data-field="columns"><option value="2">2</option><option value="3" ${c.columns===3?'selected':''}>3</option></select></div><div class="admin-inline-images">${images.map((img,i)=>mediaFields(img.media,`images.${i}.media`)).join('')}</div><button class="admin-secondary" type="button" data-add-image>＋ 添加图片</button>`;}
    if(block.type==='imageText')return `<div class="admin-field"><label>方向</label><select data-field="imagePosition"><option value="left">左图右文</option><option value="right" ${c.imagePosition==='right'?'selected':''}>左文右图</option></select></div>${mediaFields(c.image?.media,'image.media')}${field('Eyebrow','eyebrow',c.eyebrow)}${field('标题','heading',c.heading)}${field('正文（每行一段）','body',c.body,true)}`;
    if(block.type==='video')return field('标题','title',c.title)+field('视频 URL','source.url',c.source?.url)+field('Caption','caption',c.caption)+`<div class="admin-upload"><input type="file" accept="video/mp4,video/webm" data-block-video/><progress hidden></progress></div>`;
    return `<div class="admin-field"><label>留白</label><select data-field="size"><option value="small">Small</option><option value="medium" ${c.size==='medium'?'selected':''}>Medium</option><option value="large" ${c.size==='large'?'selected':''}>Large</option></select></div>`;
  }
  read(card:HTMLElement,block:Block){const base=structuredClone(defaults[block.type]??{} as any) as any;card.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-field]').forEach(input=>{const path=input.dataset.field!.split('.');let node=base;path.slice(0,-1).forEach((part,i)=>{const next=path[i+1];node[part]??=/^\d+$/.test(next)?[]:{};node=node[part];});let value:unknown=input.value;if(['description','body'].includes(path.at(-1)!))value=input.value.split('\n').map(v=>v.trim()).filter(Boolean);if(['width','height','columns'].includes(path.at(-1)!))value=Number(input.value);node[path.at(-1)!]=value;});if(block.type==='video'){base.source={kind:'external',url:base.source?.url??''};base.width=1920;base.height=1080;}if(block.type==='imageGrid'||block.type==='gallery'){base.images=(base.images??[]).filter((img:any)=>img?.media?.url).map((img:any)=>({media:img.media,fit:'contain'}));}if(block.type==='fullImage'||block.type==='imageText')base.image={...base.image,fit:base.image?.fit??'contain'};return base;}
  queueBlock(block:Block,card:HTMLElement){this.state.textContent='有未保存修改';clearTimeout(this.timer);this.timer=window.setTimeout(()=>void this.saveBlock(block,card),800);}
  async saveBlock(block:Block,card:HTMLElement){if(!this.client)return;this.state.textContent='保存中…';const content=this.read(card,block);const {error}=await this.client.from('project_blocks').update({content}).eq('id',block.id);if(error){this.state.textContent=`保存失败：${error.message}`;return;}block.content=content;this.state.textContent='已保存';}
  async add(type:string){if(!this.client)return;const {data,error}=await this.client.from('project_blocks').insert({project_id:this.projectId,type,content:defaults[type] as any,sort_order:this.blocks.length}).select().single();if(error||!data){alert(error?.message??'新增失败');return;}this.blocks.push(data);this.renderBlocks();}
  async removeBlock(block:Block){if(!this.client||!confirm('确定删除这个模块吗？'))return;const {error}=await this.client.from('project_blocks').delete().eq('id',block.id);if(error){alert(error.message);return;}this.blocks=this.blocks.filter(item=>item.id!==block.id);this.renderBlocks();await this.reorder();}
  async copy(block:Block){if(!this.client)return;const index=this.blocks.indexOf(block)+1;const {data,error}=await this.client.from('project_blocks').insert({project_id:this.projectId,type:block.type,content:block.content,sort_order:index}).select().single();if(error||!data){alert(error?.message??'复制失败');return;}this.blocks.splice(index,0,data);this.renderBlocks();await this.reorder();}
  async reorder(){if(!this.client)return;const order=[...this.list.querySelectorAll<HTMLElement>('.admin-block')].map(el=>el.dataset.id!);this.blocks=order.map(id=>this.blocks.find(block=>block.id===id)!).filter(Boolean);await Promise.all(this.blocks.map((block,index)=>this.client!.from('project_blocks').update({sort_order:index}).eq('id',block.id)));this.renderBlocks();this.state.textContent='顺序已保存';}
  async upload(file:File,kind:'cover'|'block',card?:HTMLElement,prefix='image.media'){if(!this.client)return;const progress=(kind==='cover'?this.querySelector('[data-cover-progress]'):card?.querySelector(`[data-block-upload="${prefix}"]`)?.parentElement?.querySelector('progress')) as HTMLProgressElement|null;if(progress){progress.hidden=false;progress.removeAttribute('value');}const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-');const path=`${this.projectId}/${crypto.randomUUID()}-${safe}`;const {error}=await this.client.storage.from('portfolio-media').upload(path,file,{cacheControl:'31536000',upsert:false});if(error){if(progress)progress.hidden=true;alert(`上传失败：${error.message}`);return;}const {data}=this.client.storage.from('portfolio-media').getPublicUrl(path);let width=1920,height=1080;if(file.type.startsWith('image/')){const bitmap=await createImageBitmap(file);width=bitmap.width;height=bitmap.height;bitmap.close();}const media={url:data.publicUrl,width,height,alt:file.name.replace(/\.[^.]+$/,''),caption:''};if(kind==='cover'){this.cover=media;const alt=this.form.elements.namedItem('cover_alt') as HTMLInputElement;alt.value=media.alt;this.showCover();await this.saveAll();}else if(card){for(const [key,value] of Object.entries(media)){const input=card.querySelector<HTMLInputElement>(`[data-field="${prefix}.${key}"]`);if(input)input.value=String(value);}let img=card.querySelector<HTMLImageElement>(`[data-media-group="${prefix}"] img`);if(!img){img=document.createElement('img');img.className='admin-media-preview';card.querySelector(`[data-media-group="${prefix}"]`)?.prepend(img);}img.src=media.url;const block=this.blocks.find(item=>item.id===card.dataset.id);if(block)await this.saveBlock(block,card);}if(progress)progress.hidden=true;}
  async uploadVideo(file:File,block:Block,card:HTMLElement){if(!this.client)return;const progress=card.querySelector<HTMLProgressElement>('[data-block-video] + progress');if(progress){progress.hidden=false;progress.removeAttribute('value');}const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-');const path=`${this.projectId}/${crypto.randomUUID()}-${safe}`;const {error}=await this.client.storage.from('portfolio-media').upload(path,file,{cacheControl:'31536000'});if(error){if(progress)progress.hidden=true;alert(`上传失败：${error.message}`);return;}const {data}=this.client.storage.from('portfolio-media').getPublicUrl(path);const url=card.querySelector<HTMLInputElement>('[data-field="source.url"]');if(url)url.value=data.publicUrl;await this.saveBlock(block,card);if(progress)progress.hidden=true;}
}
if(!customElements.get('admin-project-editor'))customElements.define('admin-project-editor',AdminProjectEditor);
